services:
  meilisync:
    image: ${MEILISYNC_IMAGE:-ghcr.io/ovlerfork/meilisync:latest}
    pull_policy: always
    restart: unless-stopped
    configs:
      - source: meilisync_config
        target: /meilisync/config.yml

configs:
  meilisync_config:
    file: ./config.yml
